---
- name: "Update templates"
  template:
    src:  "{{ item.src | default((item.dest | basename ()) + '.j2')}}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default(item.owner | default('root')) }}"
  with_items:
    - dest: "/etc/frr/daemons"
    - dest: "/etc/frr/vtysh.conf"
    - dest: "/etc/frr/frr.conf"
      owner: "frr"
      mode: "0640"
  notify: "frr-restart"
  when:
    - "ospf is defined"
  tags:
    - "ospf"
- name: "Start and enable frr"
  systemd:
    name: "frr"
    state: "started"
    enabled: "yes"
    daemon_reload: "yes"
  when:
    - "ospf is defined"
  tags:
    - "ospf"
